# Generated by Django 4.0.2 on 2022-08-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_passwordreset', '0003_allow_blank_and_null_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='user_agent',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='HTTP User Agent'),
        ),
    ]
