name: Full Test

on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        django-version: ['<3.0', '<3.1', '<3.2', '<3.3', '<4.1', '<4.2']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install core
        run: pip install "Django${{ matrix.django-version }}"
      - name: Install tests
        run: pip install pytest pytest-django django-ninja-extra pyjwt[crypto]
      - name: Test
        run: pytest
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Flit
        run: pip install flit
      - name: Install Dependencies
        run: flit install --symlink
      - name: Black
        run: black --check django_rest_passwordreset tests
      - name: isort
        run: isort --check django_rest_passwordreset tests
      - name: Flake8
        run: flake8 django_rest_passwordreset tests